name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/LICENSE'
      - '**/*.md'

env:
  DOCKER-CONTEXT: ./
  DOCKER-FILE: ./Dockerfile
  DOCKER-IMAGE: trainee 

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: [humble, jazzy]

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Prepare Cache Directories
        run: |
          mkdir -p /home/runner/trainee/install/
          mkdir -p /home/runner/trainee/build/
          mkdir -p /home/runner/trainee/log/
          mkdir -p /cache/vcs_hashes/

      - name: Cache VCS Hashes
        uses: actions/cache@v3
        with:
          path: /cache/vcs_hashes
          key: vcs-hashes-${{ matrix.tag }}-${{ hashFiles('repos/${{ matrix.tag }}/trainee.repos') }}
          restore-keys: |
            vcs-hashes-${{ matrix.tag }}-

      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/trainee/install/
            /home/runner/trainee/build/
            /home/runner/trainee/log/
          key: build-artifacts-${{ matrix.tag }}-${{ hashFiles('/cache/vcs_hashes/*.txt') }}
          restore-keys: |
            build-artifacts-${{ matrix.tag }}-

      - name: Set up Docker image tag
        run: echo "DOCKER_IMAGE_TAG=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/${{ env.DOCKER-IMAGE }}:${{ matrix.tag }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE }}
          tags: ${{ env.DOCKER_IMAGE_TAG }}
          build-args: |
            USERNAME=runner
            ROS_DISTRO=${{ matrix.tag }}
          ssh: default=${{ env.SSH_AUTH_SOCK }}
          cache-from: |
            type=local,src=/home/runner/trainee/install/
            type=local,src=/home/runner/trainee/build/
            type=local,src=/home/runner/trainee/log/
            type=local,src=/cache/vcs_hashes/
          cache-to: |
            type=local,dest=/home/runner/trainee/install/
            type=local,dest=/home/runner/trainee/build/
            type=local,dest=/home/runner/trainee/log/
            type=local,dest=/cache/vcs_hashes/
          no-cache: false
          push: false
